version: '3.8'

networks:
  ai-network:
    driver: bridge

volumes:
  qdrant_storage:
  postgres_data:
  redis_data:

services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - ai-network
    environment:
      - QDRANT__STORAGE__MMAP_THRESHOLD_KB=20000
      - QDRANT__STORAGE__INDEXING_THRESHOLD=50000
      - QDRANT__STORAGE__WAL_CAPACITY_MB=64
    deploy:
      resources:
        limits:
          memory: 1.5g        # 提升到1.5GB
        reservations:
          memory: 1g

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ai_knowledge
      POSTGRES_USER: ai_user
      POSTGRES_PASSWORD: ai_password
      POSTGRES_SHARED_BUFFERS: 256MB    # 翻倍
      POSTGRES_EFFECTIVE_CACHE_SIZE: 1GB # 翻倍
      POSTGRES_MAINTENANCE_WORK_MEM: 128MB
      POSTGRES_CHECKPOINT_COMPLETION_TARGET: 0.9
      POSTGRES_WAL_BUFFERS: 32MB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ai-network
    deploy:
      resources:
        limits:
          memory: 1.2g        # 提升到1.2GB
        reservations:
          memory: 800m

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 800mb --maxmemory-policy allkeys-lru --save 900 1 --save 300 10
    volumes:
      - redis_data:/data
    networks:
      - ai-network
    deploy:
      resources:
        limits:
          memory: 1g          # 提升到1GB
        reservations:
          memory: 512m

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - qdrant
      - postgres
      - redis
    extra_hosts:
      - "dify-api-1:127.0.0.1"
      - "dify-web-1:127.0.0.1"
    deploy:
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 128m
